version: "3"

services:
  mystore_frontend:
    image: santa51107/mystore_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
       - mystore_ms
    ports:
      - "8085:80"
  mystore_ms:
    image: santa51107/mystore_ms:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
       - bigstoredb
    environment:
      DB_HOST: ${POSTGRES_HOST_NAME}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DATABASE}
      URL : ${URL}
    ports:
      - "8000:8000"   
      
  bigstoredb:
    image: postgres:12
    restart: always
    environment: 
      DATABASE_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "5050:5050"
    depends_on:
      - bigstoredb

volumes:
  postgres-data:
