version: "3"

services:
  mystore_frontend:
    image: santa51107/mystore_frontend_pruebasf:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
       - mystore_ms
    ports:
      - "8085:80"
  mystore_ms:
    image: santa51107/mystore_ms_pruebasf:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_ENGINE: ${engine}
      DB_NAME: ${name}
      URL : ${URL}
    ports:
      - "8000:8000"   
      
