name: test
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: npm run test --coverage --watchAll
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
  check_result_sonar:
    needs: sonarcloud
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Failed coverage tests
      if: ${{ needs.sonarcloud.result == 'failure' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: sonarqube
        SLACK_COLOR: "#9e2a2b"
        #SLACK_ICON: https://someurl.com/logo.png
        SLACK_MESSAGE: "failed coverage tests"
        SLACK_TITLE: Failed execution
        SLACK_USERNAME: Deploy Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Successful coverage tests
      if: ${{ needs.sonarcloud.result == 'success' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: sonarqube
        SLACK_COLOR: "#52FF33"
        #SLACK_ICON: https://someurl.com/logo.png
        SLACK_MESSAGE: "successful coverage tests"
        SLACK_TITLE: Successful execution
        SLACK_USERNAME: Deploy Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}