name: Build
on:
  push:
    branches:
      - main
      - prueba
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        python-version: '3.10'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous redundant builds
      uses: styfle/cancel-workflow-actions@0.9.1
      with:
        access_token: ${{ github.token }}
  testing:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        python-version: '3.10'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Coverage testing 
      run: | 
        coverage run manage.py test -v 2
        coverage report
        coverage xml
        ls
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
