name: Deploy-backend

on:
  push:
    branches:
      - pruebaSelenium

jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0   
      - name: Set up Python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: test
        run: | 
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements_func_test.txt
          cd ..
          docker-compose -f pruebasFuncionales.yml up -d
          cd backend
          cd core
          cd func-tests
          python pruebas_funcionales.py
