name: Master Workflow

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Deploy
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: | 
        cd backend
        python -m pip install --upgrade pip
        pipenv install -r requirements.txt
        pipenv run aws configure set region us-east-1 --profile default
        pipenv run aws configure set output json --profile default
        pipenv run aws configure set aws_access_key_id ${{ secrets.ACCES_AMAZON }} --profile default
        pipenv run aws configure set aws_secret_access_key ${{ secrets.SECRET_AMAZON }} --profile default
        pipenv run zappa update
